# -*- coding: utf-8 -*-
"""train.model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITvH2t2lXO2Jev9VWp6ONdCJAPpQyysT
"""

import os
import cv2
import joblib
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Dataset path
dataset_path = "/content/sample_data/dataset"

images = []
labels = []

# Folder names
classes = ["female", "male"]

IMG_SIZE = 64

# Read images
for label, folder in enumerate(classes):
    folder_path = os.path.join(dataset_path, folder)

    if not os.path.isdir(folder_path):
        print(f"Folder not found: {folder_path}")
        continue

    for file in os.listdir(folder_path):
        img_path = os.path.join(folder_path, file)

        img = cv2.imread(img_path)

        if img is None:
            continue

        # Resize image
        img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

        # Convert to RGB (optional)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Normalize pixel values
        img = img.astype("float32") / 255.0

        # Flatten image
        img = img.flatten()

        images.append(img)
        labels.append(label)

# Convert to NumPy arrays
X = np.array(images)
y = np.array(labels)

print("Training Images:", len(X))
print("Image Shape:", X.shape)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Train model
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# Evaluate
predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)

print(f"Test Accuracy: {accuracy*100:.2f}%")

# Save model
joblib.dump(model, "female_male_model.pkl")

print("Model Saved Successfully!")